### ISSUE TITLE
Shell access enhancements

### ISSUE THREAD

**Issue by ehelms** [lago-project/lago#109]
Even though I have been only using this for a short amount of time, I find myself doing the same thing over and over. I initialize my environment, which creates environment/ which holds everything I need. In order to access the shell, I need to `cd environment/`. As i start writing scripts to automate, I don't want to store them in `environment/` because in order to "reset" or "destroy" my environment to start from scratch I have to `rm -rf environment/`. So I find myself continually changing directories from environment and back as I need to access shell or edit and execute my scripts. I could use something like screen to work around this but it might be nice to be able to do something like:

```
lago shell environment my-vm-name
```

**Comment by mykaul** [comment]
My (uncommitted) bash completion script helps a bit. Perhaps it can be
further improved.

**Comment by ifireball** [comment]
We started discussing doing something like have lago use the environment
stored in '.lago' in the current directory or the directories above
(similar to how git works), then you could just work from where your script
resides.
We cannot push that yet because we will probably need to change 'init'
syntax in an incompatible way (to make specifying the env directory
optional)

for now adding this to .bashrc may help:

lago() {
  if [[ -d "$LAGO_ENV" ]] && [[ "$1" != "init" ]]; then
   ( cd "$LAGO_ENV"; /usr/bin/lago "$@" )
  else
    /usr/bin/lago "$@"
  fi
}

Then you can just

export LAGO_ENV=/path/to/your/environment

On 11 February 2016 at 16:01, Eric D Helms <notifications@github.com> wrote:

> Even though I have been only using this for a short amount of time, I find
> myself doing the same thing over and over. I initialize my environment,
> which creates environment/ which holds everything I need. In order to
> access the shell, I need to cd environment/. As i start writing scripts
> to automate, I don't want to store them in environment/ because in order
> to "reset" or "destroy" my environment to start from scratch I have to rm
> -rf environment/. So I find myself continually changing directories from
> environment and back as I need to access shell or edit and execute my
> scripts. I could use something like screen to work around this but it might
> be nice to be able to do something like:
>
> lago shell environment my-vm-name
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/issues/109>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by ehelms** [comment]
Is the anticipation that users won't have multiple environments they are working with? I am constantly comparing this to how I use vagrant today and that often involves me having 1-3 different setups at once because I am running tests of say nightly, a release and another installation method where its nice to be able to target what I am accessing throw the command line.

**Comment by ifireball** [comment]
On 11 February 2016 at 16:32, Eric D Helms <notifications@github.com> wrote:

> Is the anticipation that users won't have multiple environments they are
> working with? I am constantly comparing this to how I use vagrant today and
> that often involves me having 1-3 different setups at once because I am
> running tests of say nightly, a release and another installation method
> where its nice to be able to target what I am accessing throw the command
> line.
>
> No, you can work with multiple environments, but  each environment will be
linked to a particular FS location (e.g. a specific source repo). Wither
you can have more then one environment linked to the same location is
something we're still discussing (it raises all kinds of problems like the
need to name the environments and how to choose the environment you are
using 'right now')

-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by david-caro** [comment]
Can you give a more detailed explanation on how are you using the multiple environments right now? Maybe we can adapt to that workflow too

**Comment by david-caro** [comment]
Actually, I don't think that the .lago feature will not be backwards compatible, as it's a default that did not exist before instead of replacing a current feature (if no prefix path specified, lookup to the .lago).
It's worth though giving it a good thought as it might be a pain to modify afterwards.

**Comment by ifireball** [comment]
The thing is that right now its "lago init PREFIX VIRT_CONFIG(aka json)",
so it seems to me you cannot specify json without specifying prefix.

On 15 February 2016 at 11:09, David Caro <notifications@github.com> wrote:

> Actually, I don't think that the .lago feature will not be backwards
> compatible, as it's a default that did not exist before instead of
> replacing a current feature (if no prefix path specified, lookup to the
> .lago).
> It's worth though giving it a good thought as it might be a pain to modify
> afterwards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/issues/109#issuecomment-184123451>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by ehelms** [comment]
The immediate use case I have is supporting multiple EL versions. In the case of doing installation testing, we'd want separate environments for EL7 and EL6 to be able to do installation testing on both. Something like:

```
workspace/
workspace/environment-el7
workspace/environment-el6
workspace/install-script.sh
```

**Comment by david-caro** [comment]
You can do that with one lago prefix, just define two vms there, one el7 and one el6, you can start one, test and then start the other (if you have resource issues) or start them in parallel and run the installation in parallel if you have enough resources, is that a solution? Is there any reason why you would need two different prefixes?

**Comment by ehelms** [comment]
I might need isolated network segments. For example, if I am testing Foreman/Katello and want to setup and control DHCP/DNS I would want to do so in isolated setups.

**Comment by david-caro** [comment]
You should be able to configure different networks too

**Comment by mykaul** [comment]
Did my fix for supporting -o in run_suite ever made it?  With it,  you can
easily run to envs in parallel in different output dirs of your choice.

**Comment by ehelms** [comment]
I guess, what I am not seeing is, if my intent is for an 'environment' to represent some specific, isolated setup, why i would want to 'gum' it up by layering in other environments? This could be a simple as me just not seeing the larger picture of what the intent of an environment is. My history is in using vagrant where we would have multiple box configuration types that represented specific setups (e.g. latest stable, nightly, developer machines).

**Comment by david-caro** [comment]
I suppose that this has not been properly defined anywhere.

As I see it there are two different concepts, the prefix, and the environment. The prefix is the workdir where lago puts any files it needs to create the environments, and an environment is just a set of networks+vms, an environment might also have multiple environments (so you can have different sets of vms+networks).

But I'm open to other ideas. Creating one prefix for each environment is another possibility (is what we have been doing on the ovirt-system-tests, though they also run on different places at different times). That's one of the reasons why the .lago dir proposal was under discussion, if we want to allow multiple prefixes and if so, how to do it

**Comment by ehelms** [comment]
This might help me understand, if my prefix is `environment`, can I run init multiple times targeting that directory with different json files? e.g.

```
lago init environment foo.json
lago init environment bar.json
```

And if I can, why would I want to do that versus:

```
lago init foo foo.json
lago init bar bar.json
```

**Comment by david-caro** [comment]
You can't, not right now at least, but what you can do is to merge foo.json and bar.json into one json file, and use that one.

At some point the idea is to be able to run:

    lago init foo.json bar.json

And get the combined prefix into $PWD/.lago, without the need to cd into it or anything and just resolving it's path as git does (checking if .lago exists on $PWD or any of the parent dirs).

The issue here is how to define the environments, there are several options I see:
* Mixing them on the same prefix: This has the advantage that you don't have to specify the prefix every time, as you can assume that it's the one in .lago
* Creating one dir per environment: This has the advantage that you have control over each environment independently, but you have to specify the prefix each time
* Creating dirs, inside the .lago one: This can help leverage both, so we can have one 'default' prefix (probably being able to change it with a subcomand, like git checkout) and you can have control over only one env (maybe add also a --environment option to the base lago command so you can also select the env for that specific command), so a possible flow for this can be:
    
    lago init --env=foo foo.json (this creates a .lago dir at $PWD)
    lago init --env=bar bar.json (this creates a .lago/bar dir at $PWD, or whatever implementation)
    lago status (runs on foo)
    lago --env=bar status (runs on bar)
    lago checkout bar (changes default to bar)
    lago status (runs on bar)
    lago --env=foo status (runs on foo)

What do you think? Maybe also extend the json file to allow specifying an environment, that will allow also creating multiple envs from the same json file, and merging json files (so you can run lago init everything.json, or lago init foo.json bar.json and init both envs)

**Comment by david-caro** [comment]
For now, #138 will allow you to use $PWD/.lago as default prefix dir (if none specified) and to run any lago command on any child of the .lago parent dir, still have to discuss the multiple envs workflows

**Comment by david-caro** [comment]
The pr #148 introduces the workdir concept, allowing to have multiple prefixes inside the same workspace
