### ISSUE TITLE
Provide mechanism to list snapshots

### ISSUE THREAD

**Issue by ehelms** [lago-project/lago#114]

**Comment by ifireball** [comment]
You can see snapshots in 'lago status' for each VM.
But yeah an environment-wide list might be easier to find and understand
since Lago does not allow per-VM snapshots for now (and maybe it shouldn't)

On 13 February 2016 at 02:07, Eric D Helms <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lago-project/lago/issues/114>.
>



-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by david-caro** [comment]
I actually does per-vm snapshots internally, and they are stored per-vm too, so that should not be hard to achieve (probably even easier than start managing globally instead)
