### ISSUE TITLE
Packaging Lago for non rpm systems

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago#309]
We want to create .deb and python packages for lago.

Initial investigation can be found in the following link: https://github.com/lago-project/lago-demo/pull/6

**Comment by kivio** [comment]
If you think about sharing Lago on PyPi there is few thinks for discussion:
1. what sens have concentrating on system specific packages -  in this case most important is python package, others are just addition
2. If we want to add support for containers and other virtualization methods then dependency for libvirt must be fast move to be plugin lazy loaded on use, it dips will be installed just if user want to use it
3. Is important to remove ovirt specific things (this is not place for that), there should be in ovirt test repositories. If is required to have ovirt here maybe it can be plugin as other virtualization method
4. Is needed to make possible to install develop version of Lago without configuration, currently it give exception because installation isn't found

**Comment by pilou-** [comment]
In order to run the oVirt test suite on Debian in a Python 2.7 virtual environment created with `--system-site-packages`, the following packages are required (at least):
* `libvirt-daemon-system`, `qemu-system-x86`, `python-guestfs`, `libguestfs-tools`, `libxslt1-dev`, `python-magic`, `yum-utils`, `koji-client`, `python-rpm`, `createrepo` Debian packages
* pip packages available on PyPI: `ovirt-engine-sdk-python` and the one listed in requirements.txt files

* `repoman` pip package (not the one available on PyPI):
    ```
    git clone https://github.com/oVirt/repoman
    pip install -r build-requirements.txt
    pip install -e .
    ```
* Fix for QEMU path: #296 or #325

**Comment by nvgoldin** [comment]
Currently blocked by: https://github.com/lago-project/lago/issues/350

**Comment by hagzag** [comment]
What is the ETA on support for non RedHat OS's e.g Ubuntu / Debian - I am now at a decision point of replacing Vagrant with a more flexible system ...

**Comment by eedri** [comment]
I think we are very close to have a formal Python packaging, see #363 and #350. 
Once we'll have Python packaging in place, adding other OS packaging like Debian will be much easier.
@gbenhaim @nvgoldin  maybe have more detailed info on it.

**Comment by mykaul** [comment]
@hagzag - why are you considering replacing vagrant? Would be good to know the reasons.

**Comment by gbenhaim** [comment]
Lago is available in PyPy.
