### ISSUE TITLE
IndexError: tuple index out of range when running lago init

### ISSUE THREAD

**Issue by dyasny** [lago-project/lago#354]
Following the documentation at http://lago.readthedocs.io/en/stable/Jenkins_Example.html on a clean RHEL 7.2 with the lago repo and EPEL enabled and lago successfully installed

```
# lago init
Traceback (most recent call last):
  File "/usr/bin/lago", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 777, in main
    parser = create_parser(cli_plugins=cli_plugins, out_plugins=out_plugins, )
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 626, in create_parser
    pkgs = e[2]
IndexError: tuple index out of range

```

**Comment by nvgoldin** [comment]
Doesn't look good - can you tell me which version you are using?(lago --version)

**Comment by dyasny** [comment]
```
# lago --version
Traceback (most recent call last):
  File "/usr/bin/lago", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 777, in main
    parser = create_parser(cli_plugins=cli_plugins,
out_plugins=out_plugins, )
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 626, in
create_parser
    pkgs = e[2]
IndexError: tuple index out of range
```

**Comment by dyasny** [comment]
# rpm -qa |grep lago
python-lago-0.27.0-1.el7.centos.noarch
lago-0.27.0-1.el7.centos.noarch

**Comment by nvgoldin** [comment]
thanks, this seems related to https://github.com/lago-project/lago/pull/352, might be regression. Can you also check which versions of pbr and stevedore you have installed?
@gbenhaim  - any ideas?

**Comment by dyasny** [comment]
python-stevedore-1.12.0-1.el7ost.noarch
python-pbr-1.8.1-2.el7ost.noarch

If you're inside the RH network I can just let you take a look, ping me on
internal IRC for access details

**Comment by nvgoldin** [comment]
I was able to replicate the issue: it was due to an old version of python-six installed(python-six.noarch 0:1.3.0-4.el7), while stevedore requires: six (>=1.9.0), so a quick workaround was to yum update python-six.
The issue in https://github.com/lago-project/lago/pull/352 is that it masked the error pkg_resources would have printed otherwise:
```
(six 1.3.0 (/usr/lib/python2.7/site-packages), Requirement.parse('six>=1.9.0'))
```
and that it makes incorrect assumptions on the ``pkg_resources.VersionConflict`` exception structure
@gbenhaim - I guess a solution would be to properly inspect the exception first, though it might be worth to rethink if we need this hack at all(maybe making a conditional RPM for el7.1 in the spec file can solve this instead).

**Comment by gbenhaim** [comment]
@nvgoldin how a condition in the spec file can help ?

**Comment by nvgoldin** [comment]
@gbenhaim - if we can map the pbr/stevedore versions needed which are available in el7.1 and don't break lago and are compatiable with eachtother, then we can add a condition just for el7.1 in the spec file. Though I'm not sure if all the above conditions can hold.
