### ISSUE TITLE
ssh is broken on el7 because of python2-paramiko

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago#440]
python2-crypto-2.6.1-13.fc24 breaks python2-paramiko-1.16.0-1.fc24, thus Lago's ssh isn't working on fc24.

This is a known issue in paramiko: https://github.com/paramiko/paramiko/pull/714

A temporary solution is to require python2-crypto-2.6.1-10.fc24 in Lago's spec file.

Example of the error:

```
14:54:47 #   File "/usr/lib/python2.7/site-packages/lago/ssh.py", line 46, in ssh
14:54:47 #     password=password,
14:54:47 #   File "/usr/lib/python2.7/site-packages/lago/ssh.py", line 346, in get_ssh_client
14:54:47 #     timeout=ssh_timeout,
14:54:47 #   File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 325, in connect
14:54:47 #     t.start_client()
14:54:47 #   File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 492, in start_client
14:54:47 #     raise e
14:54:47 # ValueError: CTR mode needs counter parameter, not IV
```

**Comment by nvgoldin** [comment]
I think it would be better to require paramiko v2.x(latest stable) instead of paramiko v1.x which we use now. paramiko v2.x  depends on https://cryptography.io/ instead of PyCrypto. In (theory :) it should just be a drop-in replacement. 
paramiko v1.x is going to be deprecated(http://www.paramiko.org/installing-1.x.html)

So other than compatibility we need to check if its packaged for all distros we support(from quick check I didn't see paramiko2 RPM on epel, but it might be hiding..).

**Comment by nvgoldin** [comment]
quick check:
fc24: only paramiko 1.x
centos7: only paramiko 1.x
fc25: paramiko 2.1.1 installed by default

so I guess we need to work around this for now, at least until fc26 is out, and then we could require paramiko2 on fc* and stick with paramiko 1.x on el7.

**Comment by nvgoldin** [comment]
mm, looking at the original bug, it seems to be around since 03/2016, so I wonder under which circumstances it fails on SSH, obviously 'shell to vm' functional test passed on fc24 many times since. Could it be that fc24 updated the version of python2-crypto recently? In fc25, I guess we are pulling paramiko v2.x, which might explain why it is working.


for references both on fc25/fc24 the version of python2-crypto is:
Version     : 2.6.1
Release     : 13.fc25

**Comment by gbenhaim** [comment]
@nvgoldin 
this is the cause https://github.com/dlitz/pycrypto/commit/8dbe0dc3eea5c689d4f76b37b93fe216cf1f00d4

**Comment by nvgoldin** [comment]
Interesting - that commit goes back to 2013, so I wonder what changed on our side.

**Comment by gbenhaim** [comment]
It was added to the fc release last week: https://src.fedoraproject.org/cgit/rpms/python-crypto.git/commit/?id=c1648a020baecf519ed84c9db766a9f102564ce5

**Comment by gbenhaim** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1418084

**Comment by nvgoldin** [comment]
cool! good catch.
I wonder if https://github.com/lago-project/lago/issues/439 is related(ssh failed which revealed a different libguestfs bug we have, though 'shell to vm' passed)

**Comment by nvgoldin** [comment]
For the record we do pull paramiko v2.x on fc25:
```
python2-paramiko.noarch 2.1.1-2.fc25  
python2-cryptography       x86_64      1.5.3-3.fc25
```

So it works :)

**Comment by ifireball** [comment]
Looks likes this not started affecting EL7 too:

http://jenkins.ovirt.org/job/test-repo_ovirt_experimental_master/5122/consoleFull

**Comment by nvgoldin** [comment]
Filled another BZ against EPEL:https://bugzilla.redhat.com/show_bug.cgi?id=1419312
With regard to fc24 - its already on updates/testing, if anyone else can give good karama, might help: https://bodhi.fedoraproject.org/updates/FEDORA-2017-6bf7d0c531

Anyways, I'll merge the workaround for now.
