### ISSUE TITLE
[RFE] move the repository syncing and serving from ost lago plugin to Lago (or its own plugin)

### ISSUE THREAD

**Issue by mykaul** [lago-project/lago#745]
The ability to sync repositories and serve them to the running VMs (or containers...) is a very useful feature for the framework and should not be limited to oVirt. Right now, it's under lago ost plugin. (lago ovirt serve for example starts the web server for it).
It'd be great if it can be moved to core Lago.

**Comment by eedri** [comment]
@gbenhaim @galitf is this something we can look at after the current RFE's being worked on?

**Comment by mykaul** [comment]
The basis was supposed to be
https://github.com/CentOS/CentOS-Dockerfiles/tree/master/nginx/centos7 ,
btw.

**Comment by gbenhaim** [comment]
@mykaul 
We moved the reposync + repoman logic to https://github.com/gbenhaim/mkrepo
You can find a container build of it in https://quay.io/repository/gbenhaim/mkrepo?tab=tags
Note that it doesn't start a web server since it can be achieved using one line of docker (docker run -v /some/content:/usr/share/nginx/html:ro -d nginx)
